DROP TABLE IF EXISTS DW_COUNTY;

CREATE TABLE DW_COUNTY AS 
    SELECT ZHVI_COUNTY.fips, ZHVI_COUNTY.state, ZHVI_COUNTY.county, ZHVI_COUNTY.date, ZHVI_COUNTY.value, AVG(HOME_INSURANCE.annual_premium) AS Avg_Annual_Premium, MORTGAGE_RATE.AverageRate, EFFECTIVE_TAX_RATE.Average_Effective_Tax_Rate, ANNUAL_INCOME.Income_Per_Capita 
    FROM (HOME_INSURANCE INNER JOIN ZIP_FIPS ON HOME_INSURANCE.zip_code = ZIP_FIPS.zip_code) 
    INNER JOIN 
    (ZHVI_COUNTY INNER JOIN MORTGAGE_RATE ON ZHVI_COUNTY.date = MORTGAGE_RATE.date)
    ON ZHVI_COUNTY.fips = ZIP_FIPS.fips AND ZHVI_COUNTY.state = ZIP_FIPS.state
    INNER JOIN EFFECTIVE_TAX_RATE ON EFFECTIVE_TAX_RATE.fips = ZHVI_COUNTY.fips
    INNER JOIN ANNUAL_INCOME ON ANNUAL_INCOME.fips = ZHVI_COUNTY.fips AND ANNUAL_INCOME.Year = strftime("%Y", ZHVI_COUNTY.date)
	GROUP BY ZHVI_COUNTY.fips, ZHVI_COUNTY.state, ZHVI_COUNTY.county, ZHVI_COUNTY.date, ZHVI_COUNTY.value, MORTGAGE_RATE.AverageRate, EFFECTIVE_TAX_RATE.Average_Effective_Tax_Rate, ANNUAL_INCOME.Income_Per_Capita;
